name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**/.*.yml'
    - '.vscode/**'
    tags-ignore:
    - '*'
  schedule:
    # we want to verify our SDKs on a constant schedule
    - cron: '0 0 * * *'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.4']

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        persist-credentials: false

    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # master
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, json, tokenizer
        coverage: xdebug

    - name: Install dependencies
      run: make install-dev

    - name: Lint code
      run: make lint

    - name: Analyze code
      run: make analyze

    - name: Run tests
      run: make test
      env:
        PC_API_KEY: ${{ secrets.PC_API_KEY }} # zizmor: ignore[secrets-outside-env]
